apiVersion: v1
kind: ConfigMap
metadata:
  name: qm1-config
  namespace: NAMESPACE
data:
  script.mqsc: |
    DEFINE CHANNEL (APP1.CHAN) CHLTYPE (SVRCONN) TRPTYPE (TCP) SSLCAUTH(OPTIONAL)  SSLCIPH('ANY_TLS13_OR_HIGHER') REPLACE
    SET CHLAUTH('APP1.CHAN') TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(NOACCESS) ACTION(REPLACE)
    SET CHLAUTH('APP1.CHAN') TYPE(SSLPEERMAP) SSLPEER('CN=app1') USERSRC(MAP) MCAUSER('app1') ACTION(REPLACE)
    SET CHLAUTH('APP1.CHAN') TYPE(SSLPEERMAP) SSLPEER('CN=QM1') USERSRC(MAP) MCAUSER('app1') ACTION(REPLACE)
    
    DEFINE CHANNEL (KAFKA.SVRCONN) CHLTYPE (SVRCONN) TRPTYPE (TCP) SSLCAUTH(OPTIONAL) MCAUSER('kafka')  REPLACE

    DEFINE CHANNEL (SYSTEMQM1CHL) CHLTYPE (SVRCONN) TRPTYPE (TCP) SSLCAUTH(REQUIRED)  SSLCIPH('ANY_TLS13_OR_HIGHER') REPLACE
    SET CHLAUTH('SYSTEMQM1CHL') TYPE(SSLPEERMAP) SSLPEER('CN=*') USERSRC(NOACCESS) ACTION(REPLACE)
    SET CHLAUTH('SYSTEMQM1CHL') TYPE(SSLPEERMAP) SSLPEER('CN=mqm') USERSRC(MAP) MCAUSER('mqm') ACTION(REPLACE)

    DEF QL(Q1)
    DEF QL(Q2)
    DEF QL(BACKOUTQ)  DEFPSIST(YES)
    ALTER QL(Q1) BOQNAME(BACKOUTQ) BOTHRESH(10)
    DEF QL(TO.KAFKA)
    DEF QL(FROM.KAFKA)

    SET AUTHREC PRINCIPAL('app1') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE(Q1) PRINCIPAL('app1') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE)
    SET AUTHREC PROFILE(Q2) PRINCIPAL('app1') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE)
    SET AUTHREC PROFILE(BACKOUTQ) PRINCIPAL('app1') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE,PASSALL)

    SET AUTHREC PRINCIPAL('bob') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ,SETALL)
    SET AUTHREC PROFILE(BACKOUTQ) PRINCIPAL('bob') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE,PASSALL,DSP)
    SET AUTHREC PROFILE(Q1) PRINCIPAL('bob') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE,SETALL)
    
    SET AUTHREC PROFILE(TO.KAFKA) PRINCIPAL('app1') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE)
    SET AUTHREC PROFILE(FROM.KAFKA) PRINCIPAL('app1') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE)
    
    SET AUTHREC PRINCIPAL('kafka') OBJTYPE(QMGR) AUTHADD(CONNECT,INQ)
    SET AUTHREC PROFILE(TO.KAFKA) PRINCIPAL('kafka') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE)
    SET AUTHREC PROFILE(FROM.KAFKA) PRINCIPAL('kafka') OBJTYPE(QUEUE) AUTHADD(PUT,GET,INQ,BROWSE)
    REFRESH SECURITY
  tls.ini: |
    Service:
        Name=AuthorizationService
        EntryPoints=14
        SecurityPolicy=UserExternal
    SSL:
        AllowTLSV13=TRUE
        OutboundSNI=HOSTNAME
        ClientRevocationChecks=DISABLED
        OCSPAuthentication=OPTIONAL
        OCSPCheckExtensions=NO
