apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/component: integration
    app.kubernetes.io/instance: orders
    app.kubernetes.io/name: ibm-mq
  name: data-mqtt-ibm-mq-0
  namespace: cp4i
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: SC_BLOCK
  volumeMode: Filesystem
