kind: ServiceAccount
apiVersion: v1
metadata:
  name: mqtt-ibm-mq
  namespace: cp4i
  labels:
    app.kubernetes.io/component: integration
    app.kubernetes.io/instance: orders
    app.kubernetes.io/name: ibm-mq
    app.kubernetes.io/version: 9.3.4.0
secrets:
  - name: orders-ibm-mq-dockercfg-p8vp7
imagePullSecrets:
  - name: sa-cp4i
  - name: ibm-entitlement-key
  - name: orders-ibm-mq-dockercfg-p8vp7
